# Copyright (C) 2018 Sean Borman <bormanst@gmail.com>.
# You should have received LICENSE.txt, a copy of the
# GNU General Public License, along with this program.
# If not, see <https://www.gnu.org/licenses/>.

spy_watch.settings:
  type: config_object
  label: 'Spy Watch settings'
  mapping:
    spy_watch:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'Spy Watch page title:'
block.settings.spy_watch_block:
  type: block_settings
  label: 'Spy Watch block'
  mapping:
    spy_watch_block_settings:
      type: text
      label: 'Spy Watch block settings'
