dist: bionic
before_install:
  - sudo mkdir -p /usr/local/formavid
  - sudo mv * /usr/local/formavid
  - sudo rm -rf /usr/local/formavid/applications/drupal8
install: skip
script: 
  - sudo /usr/local/formavid/bin/deploy_appliance "examplesitename.com" "Example Site Name" "admin@examplesitename.com" "None" "None" "None" "None" "False" "True" "False" "Pass1234" "False"
after_success:
  - |
    # verify DRUPAL
    if [[ `curl -s -k --head http://examplesitename.com | head -n 1 | grep "HTTP/1.[01] [2].."` == *"200"* ]] \
      && [[ `drush -r /var/www/drupal8/prod -l http://examplesitename.com status bootstrap | grep -q Successful` -eq 0 ]]; then
      echo "DRUPAL=TRUE"
    else
      echo "DRUPAL=FALSE"
    fi
  - |
    # verify ADMINPAGE
    if [[ `curl -u "admin:Pass1234" -s -k --head https://admin.examplesitename.com | head -n 1 | grep "HTTP/1.[01] [2].."` == *"200"* ]]; then
      echo "ADMINPAGE=TRUE"
    else
      echo "ADMINPAGE=FALSE"
    fi
  - |
    # verify INVOICENINJA
    if [[ `curl -s -k --head https://billing.examplesitename.com | head -n 1 | grep "HTTP/1.[01] [3].."` == *"302 Found"* ]]; then
      echo "INVOICENINJA=TRUE"
    else
      echo "INVOICENINJA=FALSE"
    fi
  - |
    # verify ROUNDUP
    if [[ `curl -s -k --head https://support.examplesitename.com/support/ | head -n 1 | grep "HTTP/1.[01] [2].."` == *"200"* ]]; then
      echo "ROUNDUP=TRUE"
    else
      echo "ROUNDUP=FALSE"
    fi
  - |
    # verify SHELLINABOX
    if [[ `curl -s -k --head https://examplesitename.com:12320 | head -n 1 | grep "HTTP/1.[01] [2].."` == *"200"* ]]; then
      echo "SHELLINABOX=TRUE"
    else
      echo "SHELLINABOX=FALSE"
    fi
  - |
    # verify WEBMIN
    if [[ `curl -s -k --head https://examplesitename.com:12321 | head -n 1 | grep "HTTP/1.[01] [2].."` == *"200"* ]]; then
      echo "WEBMIN=TRUE"
    else
      echo "WEBMIN=FALSE"
    fi
  - |
    # verify ADMINER
    if [[ `curl -s -k --head https://examplesitename.com:12322 | head -n 1 | grep "HTTP/1.[01] [2].."` == *"200"* ]]; then
      echo "ADMINER=TRUE"
    else
      echo "ADMINER=FALSE"
    fi
  - |
    # verify SOLR
    if [[ `curl -u "admin:Pass1234" -s -k --head http://examplesitename.com:8983/solr/#/login | head -n 1 | grep "HTTP/1.[01] [2].."` == *"200"* ]]; then
      echo "SOLR=TRUE"
    else
      echo "SOLR=FALSE"
    fi
notifications:
  email:
    on_success: change
    on_failure: change
