#!/bin/bash -e
# Copyright (C) 2018 Sean Borman <bormanst@gmail.com>.
# You should have received LICENSE.txt, a copy of the
# GNU General Public License, along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# The deployment requires root permissions so run as root or sudo.

# execute deployment script
./bin/deploy_appliance

exit 0
