#!/bin/bash -e
# Copyright (C) 2018 Sean Borman <bormanst@gmail.com>.
# You should have received LICENSE.txt, a copy of the
# GNU General Public License, along with this program.
# If not, see <https://www.gnu.org/licenses/>.

PACKAGE=adminer

# log check
MESSSAGE="Checking dependencies for ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}

# check packages
PKG_CHECK=${PACKAGE^^}
if [ -z "${!PKG_CHECK}" ]; then exit 0; fi

# check dir
set ${ADMINER_PORT:=12322}
if (grep -qF "${ADMINER_PORT}" /etc/apache2/ports.conf); then
    MESSSAGE="The ${ADMINER_PORT} port already exists. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    echo "WARNING! ${PACKAGE} may have already been initialized by this script."
    echo "WARNING! Re-running this script may corrupt existing system."
    echo "WARNING! Please review script in applications/${PACKAGE} for further details."
    echo ""
    echo ""
    exit 0
fi

# dependencies check: apache2
DEPENDS=apache2
systemctl start ${DEPENDS} && sleep 10
if ! (systemctl -q is-active ${DEPENDS}); then
    MESSSAGE="Required service ${DEPENDS} not active. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    echo "WARNING! Please ensure that ${DEPENDS} is active."
    echo ""
    echo ""
    exit 0
fi

# dependencies check: php
DEPENDS=php
if ! (hash php); then
    MESSSAGE="Required service ${DEPENDS} not active. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    echo "WARNING! Please ensure that ${DEPENDS} is active."
    echo ""
    echo ""
    exit 0
fi

# log configure
MESSSAGE="Configuring ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}

# apply overlay
OVERLAY_DIR=$1/overlay
if [ -d "${OVERLAY_DIR}" ]; then
    cp -rf ${OVERLAY_DIR}/* /
    MESSSAGE="Applied overlay for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
fi

# add apache port
sed -i "/# vim:/iListen ${ADMINER_PORT}" /etc/apache2/ports.conf

# append apache conf
MESSSAGE="Configuring apache for ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}
cat >> /etc/apache2/sites-available/zzz-admin.${SITENAME}.conf <<EOF

<VirtualHost *:${ADMINER_PORT}>
    ServerName admin.${APP_HOSTNAME}
    ServerAdmin webmaster@localhost
    SSLEngine on
    ErrorLog \${APACHE_LOG_DIR}/error.log
    CustomLog \${APACHE_LOG_DIR}/access.log combined
    AddOutputFilterByType INFLATE;SUBSTITUTE;DEFLATE text/html
    Substitute 's|<p id="breadcrumb">|<p id="breadcrumb" style="margin-top:108px;">|i'
    Substitute "s|<div id='lang'>|<div id='lang' style='margin-top:102px;'>|i"
    Substitute 's|<div id="menu">|<div id="menu" style="margin-top:113px;">|i'
    Substitute 's|<link rel="shortcut icon" type="image/x-icon" href="../adminer/static/favicon.ico">|<link rel="shortcut icon" type="image/x-icon" href="theme/favicon.ico" /><link rel="stylesheet" type="text/css" href="theme/components/asset-builds/css/header.css" />|i'
    Substitute 's|<body class=(.*)|<body  class="ltr nojs" onkeydown="bodyKeydown(event);" onclick="bodyClick(event);"><header class="header" role="banner"><div id="block-modorbiscom-branding" class="block block-system block-system-branding-block"><a href="/" title="Home" rel="home" class="site-logo"><img src="theme/logo.svg" alt="Home" /></a><div class="site-name"><a href="/" title="Home" rel="home">${SITETITLE} Adminer</a><br style="line-height:10px;" /></div></div></header>|i'
    Alias /theme /var/www/drupal9/prod/web/themes/system
    Alias /adminer/static /usr/share/adminer/adminer/static
    Alias /externals /usr/share/adminer/externals
    Alias /editor /usr/share/adminer/editor
    DocumentRoot /usr/share/adminer/adminer
    <Directory /usr/share/adminer/adminer>
        Options +FollowSymLinks
        <IfModule mod_php8.c>
            AddType application/x-httpd-php .php
            php_flag magic_quotes_gpc Off
            php_flag track_vars On
            php_flag register_globals Off
            php_value include_path .
        </IfModule>
    </Directory>
    <Directory /usr/share/adminer/editor>
        Options +FollowSymLinks
        <IfModule mod_php8.c>
            AddType application/x-httpd-php .php
            php_flag magic_quotes_gpc Off
            php_flag track_vars On
            php_flag register_globals Off
            php_value include_path .
        </IfModule>
    </Directory>
</VirtualHost>
EOF

# log completed
MESSSAGE="Package ${PACKAGE} install has completed."
echo ${MESSSAGE} | tee -a ${LOG}

exit 0
