#!/bin/bash
# Copyright (C) 2018 Sean Borman <bormanst@gmail.com>.
# You should have received LICENSE.txt, a copy of the
# GNU General Public License, along with this program.
# If not, see <https://www.gnu.org/licenses/>.

PACKAGE=mysql

# log check
MESSSAGE="Check packages: ${PACKAGE}"
echo ${MESSSAGE} >> ${LOG}

# check packages
PKG_CHECK=${PACKAGE^^}
# check dir
APP_DIR=/etc/${PACKAGE}
if [ ! -z "${!PKG_CHECK}" ] || (systemctl -q is-active ${PACKAGE}); then
    echo ""
    echo ""
    echo "WARNING! ${PACKAGE} already exists."
    echo "WARNING! ${PACKAGE} may have already been initialized by this script."
    echo "WARNING! Re-running this script may corrupt existing system."
    echo "WARNING! Please review script in applications/${PACKAGE} for further details."
    echo ""
    echo ""
    MESSSAGE="Skipping package install for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
else
    # add base packages
    export APTGETS="mariadb-server mysqltuner libdbd-mysql-perl python-mysqldb"
    export "${PACKAGE^^}"="True"
    # log export and update
    MESSSAGE="export ${PACKAGE^^}=True"
    echo ${MESSSAGE} | tee -a ${LOG} ${DEFAULT_ENVARS}
fi
