#!/bin/bash -e
# Copyright (C) 2018 Sean Borman <bormanst@gmail.com>.
# You should have received LICENSE.txt, a copy of the
# GNU General Public License, along with this program.
# If not, see <https://www.gnu.org/licenses/>.

PACKAGE=mysql

# log check
MESSSAGE="Check packages: ${PACKAGE}"
echo ${MESSSAGE} >> ${LOG}

# check packages
PKG_CHECK=${PACKAGE^^}
if [ -z "${!PKG_CHECK}" ]; then exit 0; fi

# check exists
# Note: force_utf8mb4.cnf is applied by overlay below
#       so using as a trigger
MYSQL_CONF=/etc/mysql/conf.d/force_utf8mb4.cnf
if [ -f "${MYSQL_CONF}" ]; then
    MESSSAGE="The ${MYSQL_CONF} already exists. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    echo "WARNING! ${PACKAGE} may have already been initialized by this script."
    echo "WARNING! Re-running this script may corrupt existing system."
    echo "WARNING! Please review script for further details."
    echo ""
    echo ""
    exit 0
fi

# log configure
MESSSAGE="Configuring ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}

# apply overlay
OVERLAY_DIR=$1/overlay
if [ -d "${OVERLAY_DIR}" ]; then
    cp -rf ${OVERLAY_DIR}/* /
    MESSSAGE="Applied overlay for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
fi

# set root password
MESSSAGE="Setting root password for ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}
/usr/bin/mysqladmin -u root password ${DB_PASS}

# enable db socket access
MESSSAGE="Enabling db socket access for ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}
CONF=/etc/mysql/mariadb.conf.d/50-server.cnf
sed -i '/\[mariadb\]/aplugin-load-add = auth_socket.so' ${CONF}

# restart service
MESSSAGE="Restarting service for ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}
systemctl restart ${PACKAGE}

# add admin user to database
MESSSAGE="Add admin user for ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}
ROOT_CREDS="--user=root --password=${DB_PASS}"
MYSQL_BATCH="/usr/bin/mysql ${ROOT_CREDS} --batch"
${MYSQL_BATCH} --execute "GRANT ALL PRIVILEGES ON *.* TO admin@localhost IDENTIFIED BY '${APP_PASS}' WITH GRANT OPTION; FLUSH PRIVILEGES;"

# log completed
MESSSAGE="Package ${PACKAGE} install has completed."
echo ${MESSSAGE} >> ${LOG}

exit 0
