#!/bin/bash -e
# Copyright (C) 2018 Sean Borman <bormanst@gmail.com>.
# You should have received LICENSE.txt, a copy of the
# GNU General Public License, along with this program.
# If not, see <https://www.gnu.org/licenses/>.

PACKAGE=mysql

# log check
MESSSAGE="Check packages: ${PACKAGE}"
echo ${MESSSAGE} >> ${LOG}

# check packages
PKG_CHECK=${PACKAGE^^}
if [ -z "${!PKG_CHECK}" ]; then exit 0; fi

# check exists
# Note: force_utf8mb4.cnf is applied by overlay below
#       so using as a trigger
MYSQL_CONF=/etc/mysql/conf.d/force_utf8mb4.cnf
if [ -f "${MYSQL_CONF}" ]; then
    MESSSAGE="The ${MYSQL_CONF} already exists. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    echo "WARNING! ${PACKAGE} may have already been initialized by this script."
    echo "WARNING! Re-running this script may corrupt existing system."
    echo "WARNING! Please review script for further details."
    echo ""
    echo ""
    exit 0
fi

# log configure
MESSSAGE="Configuring ${PACKAGE}..."
echo ${MESSSAGE} >> ${LOG}

# apply overlay
OVERLAY_DIR=$1/overlay
if [ -d "${OVERLAY_DIR}" ]; then
    cp -rf ${OVERLAY_DIR}/* /
    MESSSAGE="Applied overlay for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
fi

BATCH_EX="--batch --execute"
ROOT_CREDS="--user=root --password=${DB_PASS}"

# set root password
mysqladmin -u root password ${DB_PASS}

# set required global vars
QUERY="SET GLOBAL innodb_file_format=Barracuda; SET GLOBAL innodb_file_format_max=Barracuda; SET GLOBAL innodb_file_per_table=ON; SET GLOBAL innodb_large_prefix=1;"
mysql ${ROOT_CREDS} ${BATCH_EX} "${QUERY}"

# enable db socket access
CONF=/etc/mysql/mariadb.conf.d/50-server.cnf
sed -i '/\[mariadb\]/aplugin-load-add = auth_socket.so' ${CONF}

# restart service
systemctl restart ${PACKAGE}

# add admin user to database
mysql --user=root --password=${DB_PASS} --execute "CREATE USER admin@localhost IDENTIFIED BY '${APP_PASS}';"
mysql --user=root --password=${DB_PASS} --execute "GRANT ALL PRIVILEGES ON *.* TO admin@localhost WITH GRANT OPTION; FLUSH PRIVILEGES;"

# log completed
MESSSAGE="Package ${PACKAGE} install has completed."
echo ${MESSSAGE} >> ${LOG}

exit 0
