#!/bin/bash
# Copyright (C) 2018 Sean Borman <bormanst@gmail.com>.
# You should have received LICENSE.txt, a copy of the
# GNU General Public License, along with this program.
# If not, see <https://www.gnu.org/licenses/>.

PACKAGE=base

# log check
MESSSAGE="Check packages: ${PACKAGE}"
echo ${MESSSAGE} >> ${LOG}

# check packages
PKG_CHECK=${PACKAGE^^}
# check dir
APP_DIR=/var/www/admin
if [ ! -z "${!PKG_CHECK}" ] || [ -d "${APP_DIR}" ]; then
    echo ""
    echo ""
    echo "WARNING! ${PACKAGE} already exists."
    echo "WARNING! ${PACKAGE} may have already been initialized by this script."
    echo "WARNING! Re-running this script may corrupt existing system."
    echo "WARNING! Please review script in applications/${PACKAGE} for further details."
    echo ""
    echo ""
    MESSSAGE="Skipping package install for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
else
    # add base packages
    export APTGETS="apt-show-versions apt-transport-https build-essential cron-apt curl dtach etckeeper git monit openssl perl unzip libauthen-pam-perl libffi-dev libio-pty-perl libnet-ssleay-perl libssl-dev ncurses-term python-babel python-debtcollector python-dev python-dialog python-funcsigs python-requests-futures python-iso8601 python-keystoneauth1 python-monotonic python-msgpack python-netaddr python-netifaces python-oslo.config python-oslo.i18n python-oslo.utils python-oslo.serialization python-pbr python-pip python-openssl python-pyparsing python-keystoneclient python-swiftclient python-rfc3986 python-stevedore python-wrapt rsync shellinabox stunnel4"
    export "${PACKAGE^^}"="True"
    # log export
    MESSSAGE="export ${PACKAGE^^}=True"
    echo ${MESSSAGE} | tee -a ${LOG} ${FORMAVID}/bin/deploy/shell/default_envars
fi
