#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src

# Simple invoices
VERSION="2011.1"
URL="http://simpleinvoices.googlecode.com/files/simpleinvoices.${VERSION}.zip"
dl $URL $SRC

# Solr
VERSION="5.3.1"
URL="http://mirrors.advancedhosters.com/apache/lucene/solr/${VERSION}/solr-${VERSION}.tgz"
dl $URL $SRC


