#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src

# Solr
VERSION="5.5.0"
URL="http://mirrors.advancedhosters.com/apache/lucene/solr/${VERSION}/solr-${VERSION}.tgz"
dl $URL $SRC

unset PROXY

# Simple invoices
[ "$FAB_HTTP_PROXY" ] &&  http_proxy="$FAB_HTTP_PROXY"

REPO_URL=git://github.com/simpleinvoices/simpleinvoices.git
BRANCH="master"
WEBROOT=/var/www/simpleinvoices

# tested working at commit 96079e3526 - Mar 27 2015
# https://github.com/simpleinvoices/simpleinvoices/commit/96079e35269b4e513b3f8bac29ea9a2843f10236

git clone --recursive --depth 1 -b $BRANCH $REPO_URL $WEBROOT

unset http_proxy