#!/bin/sh -ex

# remove php5-xcache (#untracked-bug)
apt-get purge php5-xcache -y
rm -f /etc/php5/cli/conf.d/20-xcache.ini

DB_NAME=drupal7
DB_USER=drupal7
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/drupal7

# set proxy settings
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

# Formavid: moved to aaa_init.
# increase php cli & apache memory limits (cli for drush)
# sed -i "s|^memory_limit.*|memory_limit = 76M|" /etc/php5/cli/php.ini
# sed -i "s|^memory_limit.*|memory_limit = 64M|" /etc/php5/apache2/php.ini

# install composer
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

# install drush latest 7.x
git clone -b 7.x --depth 1 https://github.com/drush-ops/drush.git $SRC/drush
cd $SRC/drush
composer install
ln -s $SRC/drush/drush /usr/local/bin/drush
ln -s $SRC/drush/drush.complete.sh /etc/bash_completion.d/drush

mkdir -p /etc/drush
cat > /etc/drush/drushrc.php << EOF
<?php
// by default use the drupal root directory
\$options['r'] = '$WEBROOT';
EOF

# download latest drupal7 and install into existing overlay directory
drush dl drupal-7 --destination=$(dirname $WEBROOT)
# Formavid: overlay creates dir so need to cp/rm instead of mv.
# mv $(dirname $WEBROOT)/drupal-7* $WEBROOT
cp -r $(dirname $WEBROOT)/drupal-7*/* $WEBROOT
rm -rf $(dirname $WEBROOT)/drupal-7*

SETTINGS=$WEBROOT/sites/default/settings.php
cp $WEBROOT/sites/default/default.settings.php $SETTINGS
chown www-data:www-data $SETTINGS

/etc/init.d/mysql start

# Formavid: sites created with custom site stack script.
# drush site-install standard -y \
#    --account-name=$ADMIN_NAME \
#    --account-pass=$ADMIN_PASS \
#    --site-name="TurnKey Drupal7" --db-su=root --db-su-pw=$MYSQL_PASS --db-url=mysql://$DB_USER:$DB_PASS@localhost/$DB_NAME


# Formavid: modified default modules.
# download, install and enable modules
drush dl --default-major=7 \
	admin_menu \
	advanced_help \
	apachesolr \
	backup_migrate \
	captcha \
	ckeditor \
	colorbox \
	content_access \
	context \
	ctools \
	date \
	devel \
	email \
	entity \
	features \
	fivestar \
	globalredirect \
	google_analytics \
	honeypot \
	i18n \
	imce \
	jquery_ui \
	libraries \
	lightbox2 \
	link \
	logintoboggan \
	migrate \
	module_filter \
	panels \
	pathauto \
	recaptcha \
	rules \
	tagadelic \
	token \
	variable \
	views \
	views_bulk_operations \
	votingapi \
	webform \
	zen

# Formavid: modules enabled in mysql database templates used in custom site stack script.
# drush en -y \
# 	actions_permissions \
# 	admin_menu \
# 	admin_menu_toolbar \
# 	admin_views \
# 	module_filter \
# 	ctools \
# 	advanced_help \
# 	backup_migrate \
# 	entity \
# 	pathauto \
# 	token \
# 	globalredirect \
# 	honeypot \
# 	googleanalytics \
# 	ckeditor \
# 	views \
# 	views_bulk_operations \
# 	views_ui

# Formavid: want to keep toolbar.
# drush dis -y \
# 	toolbar

drush cc all

# Formavid: apachesolr module.
# Solr - update apachesolr 4.x files to work with 5.x.
CONF_SOLR=$WEBROOT/sites/all/modules/apachesolr/solr-conf/solr-4.x
sed -i "s/solr.FloatField/solr.TrieFloatField/g" $CONF_SOLR/schema.xml
sed -i "s/solr.DateField/solr.TrieDateField/g" $CONF_SOLR/schema.xml
sed -i "/solr.admin.AdminHandlers/d" $CONF_SOLR/solrconfig.xml

# configure D7 3rd party libraries path
LIBRARIES_PATH=$WEBROOT/sites/all/libraries
mkdir -p $LIBRARIES_PATH

# Formavid: getid3 module.
# configure D7 getid3 path
mkdir -p $LIBRARIES_PATH/getid3/
ln -s /usr/share/php-getid3 $LIBRARIES_PATH/getid3/getid3

# link jquery-colorbox for colorbox module
ln -s /usr/share/javascript/jquery-colorbox/ $LIBRARIES_PATH/colorbox

# configure D7 ckeditor
tar -zxf $SRC/ckeditor_*.tar.gz -C $LIBRARIES_PATH
rm -f $SRC/ckeditor_*.tar.gz

chown -R root:root $WEBROOT/sites/all

# disable poor mans cron and setup drush cron
cat >>$WEBROOT/sites/default/settings.php<< EOF

/**
 * Disable Poor Man's Cron:
 *
 * Drupal 7 enables the built-in Poor Man's Cron by default.
 * Poor Man's Cron relies on site activity to trigger Drupal's cron,
 * and is not well suited for low activity websites.
 *
 * We will use the Linux system cron and override Poor Man's Cron
 * by setting the cron_safe_threshold to 0.
 *
 * To re-enable Poor Man's Cron:
 *    Comment out (add a leading hash sign) the line below,
 *    and the system cron in /etc/cron.d/drupal7.
 */
\$conf['cron_safe_threshold'] = 0;
EOF

# Formavid: make copy for site stack template
cp $WEBROOT/sites/default/settings.php $WEBROOT/sites/default/stack.settings.php

# Formavid: need to loop through all sites in drupal stack
CRON_DRUPAL=/etc/cron.hourly/drupal7
cat >$CRON_DRUPAL<<EOF
#!/bin/bash -e
# Trigger drush cron
# Alternatively Drupal's poor mans cron: sites/default/settings.php
[ -x /usr/local/bin/drush ] || exit 0
# su www-data -c "/usr/local/bin/drush --quiet cron"
# Drupal sites will, by custom scripted design, have a "." in their directory name.
sites=()
while read -r -d ''; do
    sites+=("\$REPLY")
done < <(cd $WEBROOT/sites/; find *.* -maxdepth 0 -type d -print0)
# Run cron on the sites.
len=\${#sites[*]}
for((i=0; i<\$len; i++)); do
    su www-data -c "/usr/bin/drush -r $WEBROOT --uri=http://\${sites[\${i}]} --quiet cron"
done
EOF
chmod +x $CRON_DRUPAL

# Formavid: skip welcome page creation
# create welcome page
# MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"

# WELCOME='<p>Please follow these steps to set up and start using your website:</p><ol><li><strong>Configure your website:</strong> To get started, log in as <b>admin</b> and visit the <a href=\"/admin\">administration section</a>, where you can customize and configure all aspects of your website.</li><li><strong>Start posting content:</strong> When ready, delete this welcome and <a href=\"/node/add\">create content</a> for your website.</li></ol><p>For more information, please refer to the <a href=\"https://www.turnkeylinux.org/drupal7\">TurnKey Drupal7 release notes</a>, <a href=\"/admin/help\">help section</a>, or the <a href=\"http://drupal.org/handbooks\">online Drupal handbooks</a>. You may also post at the <a href=\"http://drupal.org/forum\">Drupal forum</a>, or view the wide range of <a href=\"http://drupal.org/support\">other support options</a> available.</p>'

# $MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node VALUES ('1', '1', 'page', 'und', 'Welcome to TurnKey Drupal 7', '1', '1', '1334908018', '1334908036', '1', '1', '0', '0', '0');"

# $MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_revision VALUES ('1', '1', '1', 'Welcome to TurnKey Drupal', '', '1334908036', '1', '1', '1', '0');"

# $MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO field_data_body VALUES ('node', 'page', '0', '1', '1', 'und', '0', '$WELCOME', '$WELCOME', 'filtered_html');"

# $MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO field_revision_body VALUES ('node', 'page', '0', '1', '1', 'und', '0', '$WELCOME', '$WELCOME', 'filtered_html');"

# $MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_comment_statistics VALUES ('1', '0', '1334908036', '', '1', '0');"

# disable footer
# $MYSQL_BATCH --database=$DB_NAME --execute "UPDATE block SET region = '-1' WHERE delta = 'powered-by';"

/etc/init.d/mysql stop

# Formavid: apache conf files created in site stack script
# configure apache
# a2dissite 000-default
# a2ensite drupal7

# Formavid: moved to aaa_init
# a2enmod rewrite

# unset proxy settings
unset HTTP_PROXY
