#!/bin/sh -ex

# configure fail2ban
SRC=/usr/local/src
PACKAGE=fail2ban
TAR=$PACKAGE.tar.gz

# Extract confs.
tar -xf $SRC/$TAR

# Overwrite default.
cp -rf $PACKAGE/* /etc/$PACKAGE

# Clean up.
rm $SRC/$TAR
rm -rf $PACKAGE
