#!/bin/sh -ex

# Formavid: clone-repo moved to downloads

DB_NAME=simpleinvoices
DB_USER=simpleinvoices
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

WEBROOT=/var/www/simpleinvoices

CONF=$WEBROOT/config/config.php

# set permissions
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/tmp
chown www-data:www-data $CONF

# Formavid: moved to aaa_init
# tweak php.ini
# PHPINI=/etc/php5/apache2/php.ini
# sed -i "s|^memory_limit.*|memory_limit = 64M|" $PHPINI

# tweak configuration
sed -i "0,/params.username/s/params.username.*/params.username = $DB_USER/" $CONF
sed -i "0,/params.password/s/params.password.*/params.password = $DB_PASS/" $CONF
sed -i "0,/params.dbname/s/params.dbname.*/params.dbname = $DB_NAME/" $CONF

sed -i "s|^encryption.default.key.*|encryption.default.key = $(mcookie)|" $CONF
sed -i "s|^nonce.key.*|nonce.key = $(mcookie)|" $CONF

sed -i "s|Europe/London|UTC|" $CONF

# Formavid: temp disable adminer
rm /etc/apache2/sites-enabled/adminer.conf

# Formavid: apache conf file created by overlay
# configure apache
# a2dissite 000-default
# a2ensite simpleinvoices
ln -s /etc/apache2/sites-available/simpleinvoices.conf /etc/apache2/sites-enabled/simpleinvoices.conf

# Formavid: moved to aaa_init
# a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
URL="http://127.0.0.1/index.php?module=install"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL "${URL}&view=structure"
$CURL "${URL}&view=essential"

rm -f /tmp/cookie

# enable authentication and set default creds
sed -i "s|^authentication.enabled.*|authentication.enabled = true|" $CONF

MD5_PASS=$(echo -n $ADMIN_PASS | md5sum | cut -d " " -f 1)
$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE si_user SET email='$ADMIN_MAIL', password='$MD5_PASS' WHERE id=1;" 

# secure sensitive files
chmod 640 $CONF

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

# Formavid: re-enable adminer
ln -s /etc/apache2/sites-available/adminer.conf /etc/apache2/sites-enabled/adminer.conf

# Formavid: remove moot files as conf will be sym-linked from /etc/simpleinvoices 
rm /etc/apache2/sites-enabled/simpleinvoices.conf
rm /etc/apache2/sites-available/simpleinvoices.conf
