#!/bin/bash -e
# regenerate admin tools page secrets

# Delete APACHE_PASSWD if exists.
APACHE_PASSWD=/usr/local/apache2/passwd/admintools
if [ -d $APACHE_PASSWD ]; then
    rm -rf $APACHE_PASSWD
fi

