#!/bin/bash -e
# regenerate roundup tracker mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/etc/roundup/tracker-config.ini
sed -i "s/^password = \(.*\)/password = $PASSWORD/" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=roundup --pass="$PASSWORD"

