#!/bin/bash -e
# set passwords

USERNAME=root

. /etc/default/inithooks

[ "$(echo $SUDOADMIN | tr [A-Z] [a-z] )" = "true" ] && USERNAME=admin

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/formavid.py --apass="$APP_PASS" --basesitename="$APP_BASESITENAME" --dbpass="$DB_PASS" email="$APP_EMAIL" --pass="$ROOT_PASS" --rpass="$ROUNDUP_PASS" --sipass="$SIMPLEINVOICES_PASS" --tld="$APP_TLD" --user="$USERNAME" --zpass="$TOOLS_PASS"
