#!/bin/bash -e
# Copyright (C) 2018 Sean Borman <bormanst@gmail.com>.
# You should have received LICENSE.txt, a copy of the
# GNU General Public License, along with this program.
# If not, see <https://www.gnu.org/licenses/>.

PACKAGE=certbot

# check install
if [ "${CERTBOT_INSTALL}" != "True" ]; then
    MESSSAGE="default_envars:CERTBOT_INSTALL not set to 'True'. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    exit 0
fi

# notify post-install PACKAGE
MESSSAGE="The script ${PACKAGE} cannot run in parallel so it should be run post-install."
echo ${MESSSAGE} | tee -a ${LOG}

# check install
# log check
MESSSAGE="Checking dependencies for ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}

# check packages
PKG_CHECK=${PACKAGE^^}
if [ -z "${!PKG_CHECK}" ]; then exit 0; fi

# dependencies check: apache2
DEPENDS=apache2
systemctl start ${DEPENDS} && sleep 10
if ! (systemctl -q is-active ${DEPENDS}); then
    MESSSAGE="Required service ${DEPENDS} not active. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    echo "WARNING! Please ensure that ${DEPENDS} is active."
    echo ""
    echo ""
    exit 0
fi

# check app dir
APP_DIR=/etc/letsencrypt/live/${APP_HOSTNAME}
if [ -d "${APP_DIR}" ]; then
    MESSSAGE="The ${APP_DIR} already exists. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    echo "WARNING! ${PACKAGE} may have already been initialized by this script."
    echo "WARNING! Re-running this script may corrupt existing system."
    echo "WARNING! Please review script for further details."
    echo ""
    echo ""
    exit 0
fi

# log configure
MESSSAGE="Configuring ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}

# create log files
PACKAGE_LOG_DIR=/var/log/letsencrypt
mkdir -p ${PACKAGE_LOG_DIR}

# apply overlay
OVERLAY_DIR=$1/overlay
if [ -d "${OVERLAY_DIR}" ]; then
    cp -rf ${OVERLAY_DIR}/* /
    MESSSAGE="Applied overlay for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
fi

# drupal project subdir
MESSSAGE="Configuring certs for ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}

WEB_ROOT=${PROJECT_DIR}/web

# get cert
# can add more webroots and domains that have DNS entries
# certbot certonly --cert-name ${APP_HOSTNAME} --webroot --agree-tos -m ${APP_EMAIL} --max-log-backups 30 -n -w ${WEB_ROOT} -d ${APP_HOSTNAME} -w /var/www/admin -d admin.${APP_HOSTNAME}
# --standalone method does not have dir perm issues that --webroot does
# need to stop apache2 for --standalone
# --apache uses apache2 plugin
# certbot certonly --cert-name ${APP_HOSTNAME} --apache --preferred-challenges http --agree-tos -m ${APP_EMAIL} --max-log-backups 30 -n -d ${APP_HOSTNAME} -d admin.${APP_HOSTNAME} -d billing.${APP_HOSTNAME} -d support.${APP_HOSTNAME}
# modify the certbot renew command in /etc/cron.d/certbot accordingly - see 'certbot help renew' for options
certbot certonly --cert-name ${APP_HOSTNAME} --apache --preferred-challenges http --agree-tos -m ${APP_EMAIL} --max-log-backups 30 -n -d ${APP_HOSTNAME}

# update apache
CONF=/etc/apache2/mods-available/ssl.conf
if [ -f "${CONF}" ]; then
    # comment any old pems
    sed -i '/^\s*SSLCertificateChainFile/s/^/#\ /g' ${CONF}
    sed -i '/^\s*SSLCertificateKeyFile/s/^/#\ /g' ${CONF}
    sed -i '/^\s*SSLCertificateFile/s/^/#\ /g' ${CONF}
    # add new pems
    sed -i "/SSLStrictSNIVHostCheck/a SSLCertificateChainFile /etc/letsencrypt/live/${APP_HOSTNAME}/fullchain.pem" ${CONF}
    sed -i "/SSLStrictSNIVHostCheck/a SSLCertificateKeyFile /etc/letsencrypt/live/${APP_HOSTNAME}/privkey.pem" ${CONF}
    sed -i "/SSLStrictSNIVHostCheck/a SSLCertificateFile /etc/letsencrypt/live/${APP_HOSTNAME}/cert.pem" ${CONF}
    # restart apache
    systemctl restart apache2
fi

# update dovecot
CONF=/etc/dovecot/conf.d/10-ssl.conf
if [ -f "${CONF}" ]; then
    # add new pems
    sed -i "s/^ssl_cert =\(.*\)/ssl_cert = <\/etc\/letsencrypt\/live\/${APP_HOSTNAME}\/fullchain.pem/" ${CONF}
    sed -i "s/^ssl_key =\(.*\)/ssl_key = <\/etc\/letsencrypt\/live\/${APP_HOSTNAME}\/privkey.pem/" ${CONF}
    # restart dovecot
    systemctl restart dovecot
fi

# update postfix
if (systemctl -q is-active postfix); then
    postconf -e "smtpd_tls_cert_file = /etc/letsencrypt/live/${APP_HOSTNAME}/fullchain.pem"
    postconf -e "smtpd_tls_cert_file = /etc/letsencrypt/live/${APP_HOSTNAME}/privkey.pem"
    postconf -e "smtpd_tls_CAfile = /etc/letsencrypt/live/${APP_HOSTNAME}/cert.pem"
    # reload postfix
    postfix reload
fi

# update shellinabox
CONF=/var/lib/shellinabox/certificate.pem
if [ -f "${CONF}" ]; then
    # create backup if none
    if [ ! -f "${CONF}.bak" ]; then mv -f /var/lib/shellinabox/certificate.pem ${CONF}.bak; fi
    # add new pems
    rm ${CONF}
    cat /etc/letsencrypt/live/${APP_HOSTNAME}/fullchain.pem /etc/letsencrypt/live/${APP_HOSTNAME}/privkey.pem > ${CONF}
    chown shellinabox:shellinabox ${CONF}
    cp -fp ${CONF} /var/lib/shellinabox/certificate-${APP_HOSTNAME}.pem
    # restart shellinabox
    systemctl restart shellinabox
fi

# update webmin
CONF=/etc/webmin/miniserv.conf
if [ -f "${CONF}" ]; then
    sed -i "s/^keyfile=\(.*\)/keyfile=\/etc\/letsencrypt\/live\/${APP_HOSTNAME}\/privkey.pem/" ${CONF}
    if grep -q "certfile" "${CONF}"; then
        sed -i "s/^certfile=\(.*\)/keyfile=\/etc\/letsencrypt\/live\/${APP_HOSTNAME}\/fullchain.pem/" ${CONF}
    else
        echo "certfile=/etc/letsencrypt/live/modorbis.com/fullchain.pem" >> ${CONF}
    fi
    # restart webmin
    systemctl restart webmin
fi

# logrotate file for letsencrypt
# MESSSAGE="Creating logrotate file for ${PACKAGE} ..."
# echo ${MESSSAGE} | tee -a ${LOG}
# 
# FILE=/etc/logrotate.d/letsencrypt
# cat > ${FILE} <<EOF
# Logrotate file for letsencrypt
# 
# ${PACKAGE_LOG_DIR}/*.log {
#         weekly
#         missingok
#         rotate 4
#         compress
#         delaycompress
#         notifempty
#         create 640 root adm
# }
# EOF

# log completed
MESSSAGE="Package ${PACKAGE} install has completed."
echo ${MESSSAGE} | tee -a ${LOG}

exit 0
