#!/bin/sh -e
#
# roundup	Startup script for the roundup http server.
#
# Version:	$Id$
#
### BEGIN INIT INFO
# Provides:          roundup
# Required-Start:    $syslog $network $remote_fs
# Required-Stop:     $syslog $network $remote_fs
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the stand-alone roundup HTTP server
# Description:       Start the stand-alone roundup HTTP server
### END INIT INFO


DESC='Roundup HTTP-Server'

BINFILE=roundup-server
EXECUTABLE=/usr/bin/$BINFILE
### to be taken from /etc/roundup/roundup-server.ini:
#PIDFILE=/var/run/roundup/server.pid
#LOGFILE=/var/log/roundup/roundup.log
CONFFILE=/etc/roundup/roundup-server.ini

# short circuit this init script in case the user prefers runit:
NOINIT=0

if test -f /etc/default/roundup; then
	. /etc/default/roundup
fi

USERUNIT=${USERUNIT:=0}


if [ ${USERUNIT} -eq 1 ] && [ -d /var/service ]; then
	# make sure there is a runit link present:
	if [ ! -e /var/service/roundup ]; then
		ln -s /etc/roundup/service /var/service/roundup
	fi
	NOINIT=1
fi

EXTRAOPTS=""

if [ X${USER} != X ]; then
	OPTIONS="-- -u ${USER:=roundup} $EXTRAOPTS -C ${CONFFILE}"
else
	OPTIONS="-- $EXTRAOPTS -C ${CONFFILE}"
fi

test -x $EXECUTABLE || exit 0

start_stop() {
	case "$1" in
	start)
		printf "Starting $DESC:"
		install -o root -g root -m 755 -d /var/run/roundup
		install -o root -g root -m 755 -d /var/run/roundup.log
		if [ ! -e $PIDFILE ]; then
		    start-stop-daemon --start --oknodo --quiet \
                        --pidfile $PIDFILE \
			--exec $EXECUTABLE $OPTIONS
		    printf " $BINFILE"
		else
		    echo "$PIDFILE exists - make sure that there is no other roundup"
		    echo "instance running. Bailing out..."
		    exit 1
		fi
		printf ".\n"
		;;
	stop)
		printf "Stopping $DESC:"
		start-stop-daemon --stop --oknodo --quiet \
                                  --pidfile $PIDFILE
		rm -f $PIDFILE
		printf " $BINFILE"
		printf ".\n"
		;;
	restart | force-reload)
		start_stop stop
		sleep 1
		start_stop start
		;;
	*)
		printf "Usage: $0 {start|stop|restart|force-reload}\n" >&2
		exit 1
		;;
	esac
}


if [ ${NOINIT} -eq 1 ]; then
	roundup-ctl "$@"
else
	start_stop "$@"
fi

exit 0

