#!/bin/bash -e
# Copyright (C) 2018 Sean Borman <bormanst@gmail.com>.
# You should have received LICENSE.txt, a copy of the
# GNU General Public License, along with this program.
# If not, see <https://www.gnu.org/licenses/>.

PACKAGE=php

# log check
MESSSAGE="Check packages: ${PACKAGE}"
echo ${MESSSAGE} >> ${LOG}

# check packages
PKG_CHECK=${PACKAGE^^}
if [ -z "${!PKG_CHECK}" ]; then exit 0; fi

# check exists
# Note: xdebug.max_nesting_level set below so using as a trigger
if [[ $(php -r "echo ini_get('memory_limit');") == "-1" ]]; then
    MESSSAGE="The memory_limit is already set. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    echo "WARNING! ${PACKAGE} may have already been initialized by this script."
    echo "WARNING! Re-running this script may corrupt existing system."
    echo "WARNING! Please review script for further details."
    echo ""
    echo ""
    exit 0
fi

# log configure
MESSSAGE="Configuring ${PACKAGE}..."
echo ${MESSSAGE} >> ${LOG}

setini() {

    file=$1
    var=$2
    val=$3

    count=$(grep -c $var $file) || true
    if [ "$count" -eq 0 ]; then
        echo "[WARNING] no match for $var in $file"
    elif [ "$count" -gt 1 ]; then
        echo "[FATAL] more than one match for $var in $file"
        exit 1
    else
        echo "  - $var=$val"
        sed -i "/^;* *$var *=/ s|^;* *$var|$var|g" $file
        sed -i "/^$var *=/ s|= *[^ ]\+|=$val|g" $file
    fi
}

# apply overlay
OVERLAY_DIR=$1/overlay
if [ -d "${OVERLAY_DIR}" ]; then
    cp -rf ${OVERLAY_DIR}/* /
    MESSSAGE="Applied overlay for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
fi

# use these defaults
set ${PHP_MEMORY_LIMIT:=256M}           # php.ini default: 128MB
set ${PHP_POST_MAX_SIZE:=16M}           # php.ini default: 8MB
set ${PHP_UPLOAD_MAX_FILESIZE:=8M}      # php.ini default: 2MB

# should be ok defaults
set ${OPCACHE_INTERNAL_STR_BUFF:=8}     # php.ini default: 4(MB)
set ${OPCACHE_FAST_SHUTDOWN:=1}         # php.ini default: 0 (disabled)
set ${OPCACHE_REVALIDATE_FREQ:=30}      # php.ini default: 2 (seconds)

# update defaults
cli_ini=cli/php.ini
for f in /etc/php/?.?/*/php.ini; do
    [ -f $f ] || continue
    echo "updating $f"
    setini $f post_max_size $PHP_POST_MAX_SIZE
    setini $f upload_max_filesize $PHP_UPLOAD_MAX_FILESIZE

    if [ "${f%%$cli_ini}" = "$f" ]; then
        # adjust settings for Apache only (not cli)
        setini $f memory_limit $PHP_MEMORY_LIMIT
        setini $f opcache.interned_strings_buffer $OPCACHE_INTERNAL_STR_BUFF
        setini $f opcache.fast_shutdown $OPCACHE_FAST_SHUTDOWN
        setini $f opcache.revalidate_freq $OPCACHE_REVALIDATE_FREQ
    else
        # adjust settings for cli only (not Apache)
        setini $f memory_limit -1
    fi
done

for f in /etc/php/?.?/cli/conf.d/20-xdebug.ini; do
    [ -f $f ] || continue
    echo "updating $f"
    echo "xdebug.max_nesting_level=256" >> $f
done

# append xdebug settings to apache2/php.init
apache2_ini=/etc/php/7.0/apache2/php.ini
cat >> ${apache2_ini} <<EOF
; x-debug settings:
;zend_extension=/usr/lib/php/20151012/xdebug.so
;xdebug.remote_enable=1
;xdebug.remote_host=127.0.0.1
;xdebug.remote_port=9000
;xdebug.remote_handler=dbgp
;xdebug.remote_mode=req
;xdebug.remote_autostart=false
;xdebug.idekey=xdebug-atom
;xdebug.remote_log=/var/log/apache2/xdebug.log
;xdebug.collect_assignments=1
;xdebug.collect_return=1
;xdebug.collect_vars=1
EOF

# log completed
MESSSAGE="Package ${PACKAGE} install has completed."
echo ${MESSSAGE} >> ${LOG}

exit 0
