#!/bin/bash -e
# Copyright (C) 2018 Sean Borman <bormanst@gmail.com>.
# You should have received LICENSE.txt, a copy of the
# GNU General Public License, along with this program.
# If not, see <https://www.gnu.org/licenses/>.

PACKAGE=proftpd

# log check
MESSSAGE="Checking dependencies for ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}

# check packages
PKG_CHECK=${PACKAGE^^}
if [ -z "${!PKG_CHECK}" ]; then exit 0; fi

# check conf
CONF=/etc/${PACKAGE}/${PACKAGE}.conf
if [ $(grep -c 'cssadmin' ${CONF}) -gt 0 ];  then
    MESSSAGE="File ${CONF} already modified. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    echo "WARNING! ${PACKAGE} may have already been initialized by this script."
    echo "WARNING! Re-running this script may corrupt existing system."
    echo "WARNING! Please review script in applications/${PACKAGE} for further details."
    echo ""
    echo ""
    exit 0
fi

# log configure
MESSSAGE="Configuring ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}

# Disable memcache module: wheezy issue until patch???
# Use dedicated ftp appliance if memcache useful/required.
# sed -i "s/LoadModule mod_tls_memcache.c/# LoadModule mod_tls_memcache.c/g" /etc/proftpd/modules.conf

# apply overlay
OVERLAY_DIR=$1/overlay
if [ -d "${OVERLAY_DIR}" ]; then
    cp -rf ${OVERLAY_DIR}/* /
    MESSSAGE="Applied overlay for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
fi

# drupal theme dir
MESSSAGE="Configuring cssadmin for ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}
THEME_DIR=${PROJECT_DIR}/web/themes

# set cssadmin dir
cat >> ${CONF} <<EOF
<Global>
  DefaultRoot ${THEME_DIR} cssadmin
</Global>
EOF

# restart service
systemctl restart ${PACKAGE}

# log completed
MESSSAGE="Package ${PACKAGE} install has completed."
echo ${MESSSAGE} | tee -a ${LOG}

exit 0
