#!/bin/bash -e
# Copyright (C) 2018 Sean Borman <bormanst@gmail.com>.
# You should have received LICENSE.txt, a copy of the
# GNU General Public License, along with this program.
# If not, see <https://www.gnu.org/licenses/>.

PACKAGE=dovecot

# log check
MESSSAGE="Checking dependencies for ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}

# check packages
PKG_CHECK=${PACKAGE^^}
if [ -z "${!PKG_CHECK}" ]; then exit 0; fi

# check ALREADY_RUN
if [ "${ALREADY_RUN}" != "False" ]; then
    MESSSAGE="The script has already been run. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    echo "WARNING! ${PACKAGE} may have already been initialized by this script."
    echo "WARNING! Re-running this script may corrupt existing system."
    echo "WARNING! Please review script in applications/${PACKAGE} for further details."
    echo ""
    echo ""
    exit 0
fi

# dependencies check: postfix
DEPENDS=postfix
systemctl start ${DEPENDS} && sleep 10
if ! (systemctl -q is-active ${DEPENDS}); then
    MESSSAGE="Required service ${DEPENDS} not active. Skipping configuration for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
    echo "WARNING! Please ensure that ${DEPENDS} is active."
    echo ""
    echo ""
    exit 0
fi

# log configure
MESSSAGE="Configuring ${PACKAGE} ..."
echo ${MESSSAGE} | tee -a ${LOG}

# apply overlay
OVERLAY_DIR=$1/overlay
if [ -d "${OVERLAY_DIR}" ]; then
    cp -rf ${OVERLAY_DIR}/* /
    MESSSAGE="Applied overlay for ${PACKAGE}."
    echo ${MESSSAGE} | tee -a ${LOG}
    echo ""
    echo ""
fi

CONF=/etc/dovecot/conf.d/10-auth.conf
sed -i "s/^auth_mechanisms =\(.*\)/auth_mechanisms = plain login/" ${CONF}

CONF=/etc/dovecot/conf.d/10-mail.conf
sed -i "s/^mail_location =\(.*\)/mail_location = maildir:~\/Maildir/" ${CONF}

CONF=/etc/dovecot/conf.d/10-master.conf
sed -i "s/#port = 110/port = 110/g" ${CONF}
sed -i "s/#port = 995/port = 995/g" ${CONF}
sed -i "s/#port = 143/port = 143/g" ${CONF}
sed -i "s/#port = 993/port = 993/g" ${CONF}
sed -i "s/#ssl = yes/ssl = yes/g" ${CONF}
sed -i "/# Postfix smtp-auth/a}" ${CONF}
sed -i "/# Postfix smtp-auth/auser = postfix" ${CONF}
sed -i "/# Postfix smtp-auth/amode = 0660" ${CONF}
sed -i "/# Postfix smtp-auth/agroup = postfix" ${CONF}
sed -i "/# Postfix smtp-auth/aunix_listener \/var\/spool\/postfix\/private\/auth {" ${CONF}

CONF=/etc/dovecot/conf.d/90-plugin.conf
sed -i "/plugin {/aautosubscribe2 = Sent" ${CONF}
sed -i "/plugin {/aautosubscribe = Trash" ${CONF}
sed -i "/plugin {/aautocreate2 = Sent" ${CONF}
sed -i "/plugin {/aautocreate = Trash" ${CONF}

# restart service
systemctl restart ${PACKAGE}

# log completed
MESSSAGE="Package ${PACKAGE} install has completed."
echo ${MESSSAGE} | tee -a ${LOG}

exit 0
